use_frameworks!

platform :ios, '9.0'

target 'RBNetworkingModule_Example' do
  pod 'RBNetworkingModule', :path => '../'

  target 'RBNetworkingModule_Tests' do
    inherit! :search_paths

    
  end
end
